name: Test

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]
jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    #что делаем
    steps:
      #выкачиваем репозиторий
      - uses: actions/checkout@v4
      #настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          #запускаем тесты
      -  uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      #скачиваем результаты тестов
      - uses: actions/checkout@v 2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #генерируем отчет
      - uses: ./allure-report-action
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      #публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history